language: node_js
# required for now due to issues related to spectre  https://github.com/travis-ci/travis-ci/issues/9024
sudo: required
node_js:
  - stable
  - 4
dist: trusty
addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
before_install:
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
after_script:
  - npm run coveralls